require_relative '../item'
require_relative '../label'
require_relative '../book'
require_relative '../game'
require_relative '../music_album'
require_relative '../genre'
require 'yaml'
require 'date'
